### ISSUE TITLE
Crash on shift clicking to a slot

### ISSUE THREAD

**Issue by Bendimester23** [Astrarre/Astrarre#1]
ABlockEntitySlot it crashing when shift clicking.
[crash-2021-04-30_18.21.11-client.txt](https://github.com/Astrarre/Astrarre/files/6406705/crash-2021-04-30_18.21.11-client.txt)

**Comment by Ueaj-Kerman** [comment]
is the game freezing? you likely did not link the slot

**Comment by Ueaj-Kerman** [comment]
yea that is the issue, I will throw a more intuitive exception

**Comment by Bendimester23** [comment]
how do i link it?

**Comment by Ueaj-Kerman** [comment]
https://github.com/Astrarre/Astrarre/wiki/Astrarre-Gui-v0#adding-inventory-slots

**Comment by Ueaj-Kerman** [comment]
Slot#link (the link method adds a "target" for the slot to shift click into). So for example if you were making a machine, you would link all the inventory slots to your machine slot

**Comment by Bendimester23** [comment]
ty
